#import <Flutter/Flutter.h>

@interface SubstrateSignFlutterPlugin : NSObject<FlutterPlugin>
@end
//Auto generated by cbindgen

char *decrypt_data(const char *data, const char *password);

char *encrypt_data(const char *data, const char *password);

char *random_phrase(uint32_t words_number);

void rust_cstr_free(char *s);

char *rust_greeting(const char *to);

bool schnorrkel_verify(const char *suri, const char *message, const char *signature);

char *substrate_address(const char *suri, uint8_t prefix);

char *substrate_sign(const char *suri, const char *text);
